/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/corgiSitting.glb
Author: smoon23_ (https://sketchfab.com/smoon23_)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/corgi-1ad76bd8293c4edd8d710213decf43d8
Title: Corgi
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function CorgiSitting(props) {
  const { nodes, materials } = useGLTF('/corgiSitting.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.18}>
        <mesh geometry={nodes.Corgi_lambert4_tex_0.geometry} material={materials.lambert4_tex} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/corgiSitting.glb')
