/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/corgi_mounts.glb
Author: arixxibaby (https://sketchfab.com/romanchenko.ksenia)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/corgi-mounts-be2cea19fdab4c03a79ff3f5116b5749
Title: corgi mounts
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshBasicMaterial } from 'three'

export default function CorgiMounts(props) {
  const { nodes, materials } = useGLTF('/corgi_mounts.glb')

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} 
            material={new MeshBasicMaterial(materials.material_0)} 
            rotation={[0, 0, 0]} 
            onPointerEnter={(event) => {
              event.stopPropagation()
              event.eventObject.scale.set(1.07, 1.07, 1.07)
              event.eventObject.material.color.set('cyan')
            }}
            onPointerLeave={(event) => {
              event.eventObject.scale.set(1/1.07, 1/1.07, 1/1.07)
              event.eventObject.material = new MeshBasicMaterial(materials.material_0)
            }}
            castShadow
            receiveShadow
            />
    </group>
  )
}

useGLTF.preload('/corgi_mounts.glb')
