/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { MeshBasicMaterial } from "three";
import { Vector3 } from "three";
import { Html } from "@react-three/drei";
import CorgiMounts from "./Corgi_mounts";
import globalState from "./stores/globalState";

export function Model(props) {
  const { nodes, materials } = useGLTF("/fantasyLand.glb");
  const crownRef = useRef()
  
  const setModalSettings = globalState((state) => state.setModalSettings)
  const setInputModalSettings = globalState((state) => state.setInputModalSettings)
  
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <CorgiMounts 
          position={[3.60, 2.5, 0.65]} 
          scale={0.004}
          onClick={() => setModalSettings([
            '/hoodiePic.JPG',
            'Mofin the Great Corgo,',
            'Como sabes, corgis are goated y they deserve everything in the world. However, la primera vez que salimos, mi ultra mega slick rizz fue interrumpido por otro animal que fue the highlight of the night. Which animal was it? Cuando sepas el answer clickea el Fantasma del Fantasmeo y escribe the answer.',
            'primary',
            'Onwards Compa...',
            true,
          ])}/>
        <group
          position={[-1.1, -0.39, 0.15]}
          rotation={[-1.5, -0.11, 3.11]}
          scale={0.001}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[-0.14, -1.92, 0.18]}
          rotation={[-1.58, 0.04, -3.14]}
          scale={0.001}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material001"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[1.57, 1, 0.19]}
          rotation={[1.59, -1.22, 0.02]}
          scale={0.001}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material011"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[-0.73, 0.77, 0.18]}
          rotation={[-1.58, 0.04, -3.14]}
          scale={0.001}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material033"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[-8.66, 2.86, 2.97]}
          rotation={[-1.58, 0.04, -3.14]}
          scale={0.001}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material041"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[-8.64, 1.87, 2.94]}
          rotation={[-1.5, -0.11, 3.11]}
          scale={0.001}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material042"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[-0.22, 2.43, 1.35]}
          rotation={[-0.66, -1.46, -2.26]}
          scale={0.0015}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material013"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[-4.53, 7.88, 2.94]}
          rotation={[-1.58, 0.21, -3.14]}
          scale={0.0015}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material044"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[3.04, 3.09, 0.54]}
          rotation={[-1.41, 1.14, 2.96]}
          scale={0.0015}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material047"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[4.19, 3.1, 0.58]}
          rotation={[-1.59, 1.29, -3.12]}
          scale={0.0015}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material048"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[-0.08, 4.27, 1.14]}
          rotation={[-1.59, 1.29, -3.12]}
          scale={0.0015}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material049"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[0.91, 11.78, 2.95]}
          rotation={[-1.58, 0.04, -3.14]}
          scale={0.0015}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material050"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[0.93, 10.55, 2.91]}
          rotation={[-1.5, -0.11, 3.11]}
          scale={0.0015}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material051"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[-0.2, 2.3, 1.27]}
          rotation={[-1.31, -1.22, -2.92]}
          scale={0.003}
        >
          <mesh
            onPointerEnter={(event) => {
              event.stopPropagation()
              event.eventObject.scale.set(1.07, 1.07, 1.07)
              event.eventObject.material.color.set('cyan')
            }}
            onPointerLeave={(event) => {
              event.eventObject.scale.set(1/1.07, 1/1.07, 1/1.07)
              event.eventObject.material = new MeshBasicMaterial(materials["birch_red_mat.001"])
            }}
            onClick={() => {
              setInputModalSettings([
              '/goatPic.jpeg', 
              'The Big Ass Tree: What is the answer?', 
              'Duck, Duck,...', 
              ['goose', 'Goose', 'ganso', 'Ganso'],
              true,])
              setModalSettings([
                '/besis.jpeg',
                'Da Big Ass Tree,',
                'Ya estamos on the latter end de este scavenger hunt y you may have noticed que no te he dicho qué es lo que estás hunting. Thankfully, you will soon know your last destination. Pero hablando de destinations, en nuestro first date, we went to a very special place, Canóvanas. En el arcade, con nuestros gamer skills we won hella tickets y nos llevamos some stuff. Specifically, qué fue lo que conseguimos para hacernos en MIT juntos? Cuando sepas el answer clickea a La Ballena.',
                'secondary',
                'To da whale 🐋...',
                false,
              ])
            }}

            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material014"].geometry}
            material= {new MeshBasicMaterial(materials["birch_red_mat.001"])}
            
          />
        </group>
        <group
          position={[-2.02, 1.71, 1.3]}
          rotation={[2.23, -1.09, 0.33]}
          scale={0.001}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material015"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[-2.2, 2.14, 1.48]}
          rotation={[3.07, -0.61, 0.19]}
          scale={0.001}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material016"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[-0.71, 0.36, 1.1]}
          rotation={[-2.18, -1.23, 1.99]}
          scale={0.001}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material017"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[-2.71, 1.35, 1.07]}
          rotation={[-1.5, -1.18, -2.93]}
          scale={0.001}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material018"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[4.28, -0.16, 0.21]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.3}
        >
          <group
            position={[0.15, 1.66, 0.15]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={8.06}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Ghost_NFT-material"].geometry}
              material={new MeshBasicMaterial(materials.Ghost)}
              onPointerEnter={(event) => {
                event.stopPropagation()
                event.eventObject.scale.set(1.07, 1.07, 1.07)
                event.eventObject.material.color.set('cyan')
              }}
              onPointerLeave={(event) => {
                event.eventObject.scale.set(1/1.07, 1/1.07, 1/1.07)
                event.eventObject.material = new MeshBasicMaterial(materials.Ghost)
              }}
              onClick={() => {
                setInputModalSettings([
                '/oop.jpeg', 
                'Fantasma del Fantasmeo: What is the answer?', 
                'Vamos a ver si todavía te acuerdas del Gran Sanju Fumble of March 19th 🐈.', 
                ['gato', 'Gato', 'cat', 'Cat'],
                true,])
                setModalSettings([
                  '/overload.jpeg',
                  'Fantasma del Fantasmeo,',
                  'You got it right, felicidades! Te acuerdas de todas esas noches de la semana pasada que me tardaba en llamarte y te decía que I was working, this is what I was doing. Pero ya no más nebuleo. Hablando de nubes, hay cierto municipio de PR que se encuentra a grandes alturas con el cual tenemos historia. Uno que según usted tiene tremendas playas. Qué pueblo será ese? Cuando sepas el answer clickea en el Shroom House.',
                  'secondary',
                  'Bon Voyage...',
                  false,
                ])
              }}
            />
          </group>
          <group
            position={[0.88, 2.63, 0.18]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={8.06}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Ghost_NFT-material001"].geometry}
              material={materials.Ghost}
            />
          </group>
          <group
            position={[-1.08, 1.41, 0.53]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={8.06}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Ghost_NFT-material002"].geometry}
              material={materials.Ghost}
            />
          </group>
          <group
            position={[-1.03, 2.5, -0.01]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={8.06}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Ghost_NFT-material003"].geometry}
              material={materials.Ghost}
            />
          </group>
          <group
            position={[0.94, 1.75, -0.27]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={8.06}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Ghost_NFT-material004"].geometry}
              material={materials.Ghost}
            />
          </group>
          <group
            position={[0.66, 1.19, -0.7]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={8.06}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Ghost_NFT-material005"].geometry}
              material={materials.Ghost}
            />
          </group>
          <group
            position={[-1.05, 1.72, -0.22]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={8.06}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Ghost_NFT-material006"].geometry}
              material={materials.Ghost}
            />
          </group>
          <group
            position={[0.64, 0.89, 0.34]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={8.06}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Ghost_NFT-material007"].geometry}
              material={materials.Ghost}
            />
          </group>
          <group
            position={[-0.63, 1.8, -0.73]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={8.06}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Ghost_NFT-material008"].geometry}
              material={materials.Ghost}
            />
          </group>
          <group
            position={[0.65, 1.29, 0.04]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={8.06}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Ghost_NFT-material009"].geometry}
              material={materials.Ghost}
            />
          </group>
          <group
            position={[0.64, 1.27, 0.05]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={8.06}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Ghost_NFT-material010"].geometry}
              material={materials.Ghost}
            />
          </group>
          <group
            position={[0.77, 1.46, 0.02]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={8.06}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Ghost_NFT-material011"].geometry}
              material={materials.Ghost}
            />
          </group>
          <group
            position={[0.66, 1.58, 0.02]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={8.06}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Ghost_NFT-material012"].geometry}
              material={materials.Ghost}
            />
          </group>
          <group
            position={[0.59, 1.38, 0.22]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={8.06}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Ghost_NFT-material013"].geometry}
              material={materials.Ghost}
            />
          </group>
          <group
            position={[-0.51, 1.17, 0.34]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={8.06}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Ghost_NFT-material014"].geometry}
              material={materials.Ghost}
            />
          </group>
          <group
            position={[-0.41, 1.33, 0.4]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={8.06}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Ghost_NFT-material015"].geometry}
              material={materials.Ghost}
            />
          </group>
          <group
            position={[-0.49, 1.44, 0.33]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={8.06}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Ghost_NFT-material016"].geometry}
              material={materials.Ghost}
            />
          </group>
          <group
            position={[-0.65, 1.25, 0.45]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={8.06}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Ghost_NFT-material017"].geometry}
              material={materials.Ghost}
            />
          </group>
          <group
            position={[-0.52, 1.16, 0.38]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={8.06}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Ghost_NFT-material018"].geometry}
              material={materials.Ghost}
            />
          </group>
        </group>
        <group
          position={[-1.76, 2.15, 1.48]}
          rotation={[-1.46, -0.98, 3.06]}
          scale={0.001}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material019"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[-3.5, 8.91, 4.31]}
          rotation={[0, 0, 1.02]}
          scale={[0.15, 0.15, 0.16]}
        >
          <mesh
            onPointerEnter={(event) => {
              event.stopPropagation()
              event.eventObject.scale.set(1.07, 1.07, 1.07)
              event.eventObject.material.color.set('cyan')
            }}
            onPointerLeave={(event) => {
              event.eventObject.scale.set(1/1.07, 1/1.07, 1/1.07)
              event.eventObject.material = new MeshBasicMaterial(materials.birch_red_mat)
            }}
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material077"].geometry}
            material={new MeshBasicMaterial(materials.birch_red_mat)}
          />
        </group>
        <group position={[0.92, -2.16, 0.16]} scale={[0.36, 0.36, 0.02]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[1.52, 0.43, 0.07]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material005"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[-0.48, -1.57, 0.07]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material006"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[2.93, -0.17, 0.16]} scale={[0.36, 0.36, 0.02]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material007"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[1.64, 0.05, 0.18]}
          rotation={[0, 0, 0.58]}
          scale={[0.09, 0.09, 0.03]}
        >
          <mesh
            onPointerEnter={(event) => {
              event.stopPropagation()
              event.eventObject.scale.set(1.07, 1.07, 1.07)
              event.eventObject.material.color.set('cyan')
            }}
            onPointerLeave={(event) => {
              event.eventObject.scale.set(1/1.07, 1/1.07, 1/1.07)
              event.eventObject.material = new MeshBasicMaterial(materials["birch_red_mat.001"])
            }}
            onClick={() => {
              setInputModalSettings([
              '/brava.jpeg', 
              'Shroom House: What is the answer?', 
              'Voy a ti you got this <3', 
              ['Aibonito', 'aibonito'],
              true,])
              setModalSettings([
                '/arrebato.JPG',
                'Shroom House,',
                "Woot Woot! Bienvenida al Shroom House. Drugs, sometimes they're great, sometimes not so much. Te acuerdas de la vez que llegué a tu cuarto on shrooms? On that note, ese día fui a Commons con Miguel y me acordé de la vez que we went allí on a little date y vimos una nena persiguiendo a unos birds? What kind of bird was it? Cuando sepas el answer clickea Da Big Ass Tree...",
                'primary',
                'Continue (⌐■_■)...',
                false,
              ])
            }}
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material008"].geometry}
            material={new MeshBasicMaterial(materials["birch_red_mat.001"])}
          />
        </group>
        <group position={[2.93, 1.84, 0.59]} scale={[0.36, 0.36, 0.02]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material008"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[-1.07, 1.84, 1.11]} scale={[0.36, 0.36, 0.02]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material025"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[-1.18, 1.58, 0.47]} scale={0.1}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material026"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[-1.07, 3.86, 1.11]} scale={[0.36, 0.36, 0.02]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material045"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[3.67, -1.68, 0.19]} scale={[0.16, 0.16, 0.02]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material052"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[-0.48, 0.44, 0.07]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material009"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[2.93, -2.16, 0.16]} scale={[0.36, 0.36, 0.02]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material010"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[3.89, 1.5, 0.28]} scale={[0.1, 0.15, 0.06]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material023"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[4.42, 2.13, 0.28]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.15, 0.15, 0.09]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material020"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[2.82, 1.58, 0.3]} scale={[0.1, 0.1, 0.05]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material012"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[4.42, 2.3, 0.31]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.15, 0.1, 0.07]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material021"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[3.83, 1.5, 0.44]} scale={[0.04, 0.15, 0.11]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material011"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[2.56, 1.55, 0.27]} scale={[0.1, 0.15, 0.09]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material013"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[4.37, 1.56, 0.28]} scale={[0.1, 0.15, 0.06]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material014"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[3.13, 1.38, 0.36]} scale={[0.1, 0.15, 0.11]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material015"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[4.25, 1.56, 0.3]} scale={[0.1, 0.1, 0.05]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material016"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[4.46, 1.59, 0.3]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.13, 0.09, 0.1]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material017"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[4.39, 1.82, 0.27]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.13, 0.1, 0.08]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material024"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[4.47, 1.48, 0.09]}
          rotation={[0, 0, 0.48]}
          scale={[0.04, 0.06, 0.05]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material018"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[3.3, 1.5, 0.44]} scale={[0.04, 0.15, 0.11]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material022"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[-1.45, 1.55, 0.41]} scale={[0.1, 0.15, 0.18]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material027"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[0.05, 1.56, 0.42]} scale={[0.13, 0.2, 0.16]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material028"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[-0.88, 1.38, 0.53]} scale={[0.1, 0.15, 0.26]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material029"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[-0.11, 1.57, 0.47]} scale={[0.13, 0.13, 0.12]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material030"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[0.46, 1.59, 0.47]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.13, 0.09, 0.2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material031"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[0.47, 1.48, 0.05]}
          rotation={[0, 0, 0.48]}
          scale={[0.04, 0.06, 0.1]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material032"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[0.41, 2.13, 0.41]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.15, 0.15, 0.18]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material033"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[0.41, 2.3, 0.41]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.15, 0.1, 0.18]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material034"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[-0.57, 1.49, 0.42]} scale={[0.13, 0.2, 0.16]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material035"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[0.35, 1.84, 0.39]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.13, 0.1, 0.15]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material036"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[0.49, 3.38, 0.35]}
          rotation={[-Math.PI, 0, -Math.PI / 2]}
          scale={[-0.13, -0.09, -0.26]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material037"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[0.41, 2.68, 0.41]}
          rotation={[-Math.PI, 0, -Math.PI / 2]}
          scale={[-0.15, -0.1, -0.18]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material038"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[0.35, 3.07, 0.31]}
          rotation={[Math.PI, 0.05, -Math.PI / 2]}
          scale={[-0.13, -0.14, -0.19]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material039"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[4.42, 3.18, 0.28]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.15, 0.15, 0.09]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material041"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[0.39, 1.49, 0.42]} scale={[0.13, 0.2, 0.4]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material040"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[4.42, 3.35, 0.31]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.15, 0.1, 0.07]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material042"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[4.39, 2.87, 0.27]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.13, 0.1, 0.08]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material043"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[4.46, 2.64, 0.3]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.13, 0.09, 0.1]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material044"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[3.22, -1.03, 0.19]} scale={[0.12, 0.12, 0.02]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material053"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[3.11, -1.19, 0.19]}
          rotation={[0.02, 0, 0]}
          scale={[0.12, 0.12, 0.02]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material054"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[-0.9, 0.62, 0.19]} scale={[0.12, 0.12, 0.02]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material055"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[4.29, -2.31, 0.19]}
          rotation={[0.02, 0, 0]}
          scale={[0.12, 0.12, 0.02]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material056"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[0.46, 3.7, 0.22]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.26, 0.09, 0.2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material046"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[4.28, -0.15, 0.19]}
          rotation={[0.02, 0, 0]}
          scale={[0.12, 0.12, 0.02]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material057"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[0.41, 4.32, 0.41]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.15, 0.1, 0.18]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material047"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[3.46, -1.7, 0.21]} scale={[0.06, 0.06, 0.02]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material058"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[0.22, 4, 0.13]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.2, 0.2, 0.18]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material048"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[0.46, 5.41, 0.33]}
          rotation={[-Math.PI, 0, -Math.PI / 2]}
          scale={[-0.13, -0.09, -0.26]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material049"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[0.41, 4.7, 0.41]}
          rotation={[-Math.PI, 0, -Math.PI / 2]}
          scale={[-0.15, -0.1, -0.18]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material073"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[0.35, 5.09, 0.31]}
          rotation={[Math.PI, 0.05, -Math.PI / 2]}
          scale={[-0.13, -0.14, -0.19]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material050"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[0.39, 3.51, 0.42]} scale={[0.13, 0.2, 0.4]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material051"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[2.77, -2.39, 0.18]} scale={[0.05, 0.05, 0.02]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material059"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[0.96, -0.96, 0.19]} scale={[0.16, 0.16, 0.02]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material060"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[1.26, -0.98, 0.19]} scale={[0.05, 0.05, 0.02]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material061"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[4.22, -0.96, 0.31]} scale={0.18}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material063"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[0.02, 4.92, 1.32]}
          rotation={[0, 0, -0.88]}
          scale={[0.35, 0.35, 0.3]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material067"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[-0.79, 4.75, 1.5]}
          rotation={[0, 0, -1.64]}
          scale={[0.5, 0.39, 0.5]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material068"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[-0.09, 2.72, 1.35]}
          rotation={[0, 0, -1.14]}
          scale={0.3}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material069"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[5.16, -1.13, 0.19]}
          rotation={[0.02, 0, 0]}
          scale={[0.13, 0.13, 0.01]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material070"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[4.99, -1.6, 0.18]}
          rotation={[0.02, 0, 0]}
          scale={[0.09, 0.09, 0.01]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material071"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[5.99, -1.97, 0.19]}
          rotation={[0.02, 0, 0]}
          scale={[0.12, 0.12, 0.01]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material072"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[-4.48, 9.3, 3.26]}
          rotation={[0, 0, -1.81]}
          scale={[0.3, 0.23, 0.5]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material078"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[-3.56, 8.89, 2.91]}
          rotation={[0, 0, -1.28]}
          scale={[0.35, 0.35, 0.14]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Material_001-material001"].geometry}
            material={materials["Material.015"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material075"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[-9.32, 2.46, 3.1]}
          rotation={[0, 0, -1.18]}
          scale={[0.2, 0.2, 0.17]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material076"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[3.66, -1.39, 0.17]} scale={[0.36, 0.36, 0.02]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Material_001-material002"].geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group position={[3.66, 0.57, 0.17]} scale={[0.36, 0.36, 0.02]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Material_001-material003"].geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group position={[1.65, -1.39, 0.17]} scale={[0.36, 0.36, 0.02]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Material_001-material004"].geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group position={[1.65, 0.57, 0.17]} scale={[0.36, 0.36, 0.02]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Material_001-material005"].geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group position={[-0.35, -1.39, 0.17]} scale={[0.36, 0.36, 0.02]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Material_001-material006"].geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          position={[0.93, -1.64, 0.34]}
          rotation={[0, 0, -1.18]}
          scale={[0.24, 0.24, 0.21]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material064"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[-0.86, -2.14, 0.36]}
          rotation={[0, 0, -1.64]}
          scale={0.27}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material065"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[-0.35, 0.57, 0.17]} scale={[0.36, 0.36, 0.02]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Material_001-material007"].geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group position={[3.66, 2.61, 0.6]} scale={[0.36, 0.36, 0.02]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Material_001-material008"].geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group position={[-0.37, 2.61, 1.12]} scale={[0.36, 0.36, 0.02]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Material_001-material009"].geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group position={[-0.37, 4.61, 1.12]} scale={[0.36, 0.36, 0.02]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Material_001-material010"].geometry}
            material={materials["Material.015"]}
          />
        </group>
        <group
          position={[0.78, 11.23, 2.92]}
          rotation={[0, 0, -0.63]}
          scale={[0.21, 0.21, 0.14]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Material_001-material011"].geometry}
            material={materials["Material.015"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material079"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[0.08, 11.28, 3.12]}
          rotation={[0, 0, -1.18]}
          scale={[0.25, 0.25, 0.22]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material080"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[6.12, -1.74, 0.18]}
          rotation={[0.02, 0, 0]}
          scale={[0.05, 0.05, 0.01]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material081"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[-8.77, 2.42, 2.94]}
          rotation={[0, 0, -0.63]}
          scale={[0.17, 0.17, 0.11]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Material_001-material"].geometry}
            material={materials["Material.015"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material074"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[4.48, 0.84, 0.28]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.02}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material032"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[1.89, 1.23, 0.28]}
          rotation={[Math.PI, -1.57, 0]}
          scale={0.02}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material021"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[2.37, 0.79, 0.29]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.02}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material034"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[0.65, 1.07, 0.33]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.02}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material022"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[2.63, 1.97, 0.71]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={0.02}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material035"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[2.63, 2.93, 0.71]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={0.02}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material036"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[-1.34, 0.76, 0.29]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={0.02}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material020"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[3.57, 1.02, 0.29]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[0.09, 0.06, 0.08]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material019"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group position={[5.54, -1.6, 0.1]} scale={0.09}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material062"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[1.32, -0.15, 0.22]}
          rotation={[0, 0, 0.23]}
          scale={2.97}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material002"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[-0.16, 2.54, 1.18]}
          rotation={[0, 0, 0.31]}
          scale={4.58}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material002"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[2.1, 0.47, 0.27]}
          rotation={[0, 0, 0.65]}
          scale={2.61}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material005"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[1.05, 0.29, 0.2]}
          rotation={[0, 0, -2.02]}
          scale={2.45}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material006"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[1.96, 0.9, 0.25]}
          rotation={[0, 0, 0.31]}
          scale={2.44}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material007"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[0.28, 2.32, 1.19]}
          rotation={[0, 0, -0.33]}
          scale={5.09}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material003"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[-0.92, 2.06, 1.21]}
          rotation={[0, 0, 0.65]}
          scale={5.67}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material009"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[-0.26, -2.15, 0.22]}
          rotation={[0, 0, 0.54]}
          scale={2.71}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material010"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[-0.14, -1.22, 0.3]}
          rotation={[0, 0, 0.23]}
          scale={4.73}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material004"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[1.2, -2.05, 0.24]}
          rotation={[0.16, -0.09, -0.61]}
          scale={1.19}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material024"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[1.01, -2.37, 0.31]}
          rotation={[0.16, -0.09, -0.61]}
          scale={1.63}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material023"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[-0.61, 1.73, 1.17]}
          rotation={[0, 0, 0.23]}
          scale={5.08}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material001"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[1.14, -0.21, 0.24]}
          rotation={[0.16, -0.09, -0.61]}
          scale={1.58}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material025"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[-0.58, 2.2, 1.18]}
          rotation={[0, 0, -2.02]}
          scale={3.4}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material003"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[1.33, -0.02, 0.31]}
          rotation={[0.16, -0.09, -0.61]}
          scale={1.61}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material026"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[1.23, -0.45, 0.32]}
          rotation={[0.16, -0.09, -0.61]}
          scale={1.61}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material027"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[2.9, 1.23, 0.22]}
          rotation={[0, 0, 0.47]}
          scale={3.22}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material030"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[3.2, 0.89, 0.29]}
          rotation={[0.16, -0.09, -0.61]}
          scale={1.21}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material031"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[1.06, -1.8, 0.36]}
          rotation={[-0.14, -0.22, 0.64]}
          scale={1.68}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat-material066"].geometry}
            material={materials.birch_red_mat}
          />
        </group>
        <group
          position={[3.9, -0.93, 0.27]}
          rotation={[0.16, -0.09, -0.61]}
          scale={1.01}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material037"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[3.94, -0.74, 0.25]}
          rotation={[0.16, -0.09, -0.61]}
          scale={1.17}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material038"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[4.42, -0.74, 0.22]}
          rotation={[-0.18, 0.16, -0.92]}
          scale={1.96}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material039"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[-3.64, 7.97, 3.03]}
          rotation={[0, 0, -2.2]}
          scale={[3.46, 3.46, 4.86]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material043"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[-3.98, 7.66, 3.04]}
          rotation={[0, 0, 0.38]}
          scale={7.24}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material045"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[-2.62, 9.92, 3.04]}
          rotation={[0, 0, -0.24]}
          scale={7.97}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material046"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[0.19, 2.46, 1.15]}
          rotation={[0, 0, 0.31]}
          scale={2.82}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material004"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[-1.16, 0.76, 0.24]}
          rotation={[1.52, 0.74, 0.08]}
          scale={[0.25, 0.18, 0.25]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material030"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[0.78, -0.92, 0.08]}
          rotation={[1.52, 0.74, 0.08]}
          scale={[0.44, 0.32, 0.44]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material001"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[0.78, -0.92, 0.08]}
          rotation={[1.52, 0.74, 0.08]}
          scale={[0.44, 0.32, 0.44]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material002"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[-1.17, -1.81, 0.18]}
          rotation={[1.52, 0.74, 0.08]}
          scale={[0.5, 0.36, 0.5]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material003"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[-1.27, -1.87, 0.18]}
          rotation={[1.52, 0.74, 0.08]}
          scale={[0.44, 0.32, 0.44]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material004"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[0.78, -0.92, 0.08]}
          rotation={[1.52, 0.74, 0.08]}
          scale={[0.44, 0.32, 0.44]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[0.78, -0.92, 0.13]}
          rotation={[1.52, 0.74, 0.08]}
          scale={[0.6, 0.43, 0.6]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material005"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[-1.27, -1.83, 0.19]}
          rotation={[1.52, 0.74, 0.08]}
          scale={[0.44, 0.32, 0.44]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material006"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[2.47, 0.82, 0.22]}
          rotation={[-3.06, 1.45, -1.61]}
          scale={[0.35, 0.25, 0.35]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material025"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[2.41, -0.17, 0.22]}
          rotation={[2.28, 1.19, -0.66]}
          scale={[0.27, 0.19, 0.27]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material026"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[0.92, -0.08, 0.22]}
          rotation={[-3.06, 1.45, -1.61]}
          scale={[0.35, 0.25, 0.35]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material027"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[-0.15, 2.31, 1.2]}
          rotation={[1.62, 1.39, -0.08]}
          scale={[0.36, 0.26, 0.36]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material028"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[-0.73, 0.25, 0.24]}
          rotation={[1.4, 1.33, 0.21]}
          scale={[0.3, 0.22, 0.3]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material031"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[2.79, 1.14, 0.22]}
          rotation={[1.87, 1.16, -0.23]}
          scale={[0.24, 0.17, 0.24]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material029"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[-1.07, 0.28, 0.22]}
          rotation={[1.52, 0.74, 0.08]}
          scale={[0.3, 0.21, 0.3]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material032"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[-1.13, 0.01, 0.22]}
          rotation={[1.52, 0.74, 0.08]}
          scale={[0.26, 0.19, 0.26]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material033"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[1.24, -1.77, 0.22]}
          rotation={[1.53, 0.5, 0.07]}
          scale={[0.35, 0.25, 0.35]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material034"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[4.33, -1.2, 0.22]}
          rotation={[1.53, -0.23, 0.04]}
          scale={[0.31, 0.22, 0.31]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material035"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[0.78, -0.92, 0.08]}
          rotation={[1.52, 0.74, 0.08]}
          scale={[0.44, 0.32, 0.44]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material007"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[0.78, -0.92, 0.08]}
          rotation={[1.52, 0.74, 0.08]}
          scale={[0.44, 0.32, 0.44]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material008"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[0.78, -0.92, 0.08]}
          rotation={[1.52, 0.74, 0.08]}
          scale={[0.44, 0.32, 0.44]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material009"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[0.78, -0.92, 0.13]}
          rotation={[1.52, 0.74, 0.08]}
          scale={[0.6, 0.43, 0.6]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material010"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[-0.83, -1.28, 0.23]}
          rotation={[1.52, 0.74, 0.08]}
          scale={[0.37, 0.27, 0.37]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material011"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[-0.79, -1.23, 0.23]}
          rotation={[1.52, 0.74, 0.08]}
          scale={[0.37, 0.27, 0.37]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material012"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[-1.07, -1.35, 0.22]}
          rotation={[1.52, 0.74, 0.08]}
          scale={[0.37, 0.27, 0.37]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material013"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[-1.13, -1.46, 0.22]}
          rotation={[1.52, 0.74, 0.08]}
          scale={[0.37, 0.27, 0.37]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material014"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[-1.23, -1.33, 0.22]}
          rotation={[1.52, 0.74, 0.08]}
          scale={[0.37, 0.27, 0.37]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material015"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[0.78, -0.92, 0.08]}
          rotation={[1.52, 0.74, 0.08]}
          scale={[0.44, 0.32, 0.44]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material016"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[-1.15, -1.23, 0.22]}
          rotation={[1.52, 0.74, 0.08]}
          scale={[0.37, 0.27, 0.37]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material017"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[1.94, 0.24, 0.23]}
          rotation={[1.48, 1.12, 0.13]}
          scale={[0.29, 0.21, 0.29]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material018"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[1.24, 0.02, 0.24]}
          rotation={[1.51, 0.91, 0.1]}
          scale={[0.35, 0.25, 0.35]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material019"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[2.15, 0.72, 0.26]}
          rotation={[1.51, 0.91, 0.1]}
          scale={[0.26, 0.19, 0.26]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material020"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[1.48, 1.06, 0.26]}
          rotation={[1.52, 0.61, 0.07]}
          scale={[0.36, 0.26, 0.36]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material021"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[0.68, 0.47, 0.24]}
          rotation={[1.04, 1.49, 0.58]}
          scale={[0.39, 0.28, 0.39]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material022"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[1.02, 1.07, 0.25]}
          rotation={[1.52, 0.61, 0.07]}
          scale={[0.43, 0.31, 0.43]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material023"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[-0.54, -2.35, 0.21]}
          rotation={[1.28, 1.43, 0.33]}
          scale={[0.21, 0.15, 0.21]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["mid-material024"].geometry}
            material={materials.material}
          />
        </group>
        <group
          position={[-2.28, 0.99, 2.55]}
          rotation={[1.1, 0.01, -0.08]}
          scale={0.015}
        >
          <mesh
            ref={crownRef}
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material012"].geometry}
            material={new MeshBasicMaterial(materials["birch_red_mat.001"])}
          />
        </group>
        <group
          position={[-2.55, 1.1, 1.59]}
          rotation={[-0.17, 0.2, 0.17]}
          scale={0.02}
        >
          <mesh
            onPointerEnter={(event) => {
              event.stopPropagation()
              event.eventObject.scale.set(1.07, 1.07, 1.07)
              event.eventObject.material.color.set('cyan')
              crownRef.current.scale.set(1.07, 1.07, 1.07)
              crownRef.current.material.color.set('cyan')
            }}
            onPointerLeave={(event) => {
              event.eventObject.scale.set(1/1.07, 1/1.07, 1/1.07)
              event.eventObject.material = new MeshBasicMaterial(materials.SpermWhale)
              crownRef.current.scale.set(1/1.07, 1/1.07, 1/1.07)
              crownRef.current.material = new MeshBasicMaterial(materials["birch_red_mat.001"])
            }}
            onClick={() => {
              setInputModalSettings([
              '/iconica.jpeg', 
              'La Ballenota: What is the answer?', 
              'I have a very permanent one...', 
              ['tatoos', 'tatuaje', 'Tatuaje', 'Tatoos', 'tatuajes', 'Tatuajes', 'Tatoo', 'tatoo'],
              true,])
              setModalSettings([
                '/besis.jpeg',
                'La Ballenota,',
                'Ya estamos on the latter end de este scavenger hunt y you may have noticed que no te he dicho qué es lo que estás hunting. Thankfully, you will soon know your last destination. Pero hablando de destinations, en nuestro first date, we went to a very special place, Canóvanas. En el arcade, con nuestros gamer skills we won hella tickets y nos llevamos some stuff. Specifically, qué fue lo que conseguimos para hacernos en MIT juntos? Cuando sepas el answer clickea a La Ballenota.',
                'secondary',
                'To da whale 🐋...',
                false,
              ])
            }}
            castShadow
            receiveShadow
            geometry={nodes["SpermWhale-material"].geometry}
            material={new MeshBasicMaterial(materials.SpermWhale)}
          />
        </group>
        <group
          position={[-12.8, 4.33, 1.11]}
          rotation={[Math.PI / 2, 1.12, 0]}
          scale={0.01}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material029"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[-3.79, 11.34, 3.03]}
          rotation={[1.47, -0.07, -0.1]}
          scale={0.005}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material040"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
        <group
          position={[-6.22, 5.94, 2.02]}
          rotation={[Math.PI / 2, 0.24, 0]}
          scale={0.01}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["birch_red_mat_001-material028"].geometry}
            material={materials["birch_red_mat.001"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/fantasyLand.glb");